### ISSUE TITLE
i created custom fill triggers for each soilmod filltype - trying to get courseplay to recognize them

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#13]
https://github.com/Courseplay/courseplay/issues/1080

i wanted to reference this here in case you had any insight into why courseplay does not fill with my custom triggers like they should.

CP aside, they are working as planned.. they will select the proper filltype if the sprayer is empty, or fill the selected filltype if already partially full.

**Comment by sootysax** [comment]
any insight into why these are not working?

**Comment by DeckerMMIV** [comment]
Do you have a download link to a _ready-made_ zip-mod of those placeable fill-triggers, so I don't have to spend time to make some myself?

At the moment, as I have not tried anything yet, is that the Courseplay script-code probably only react to the game's basic/default fill-trigger type `fertilizer` or `liquidManure` - or as JakobT writes, that the implements currentFillType is `Fillable.FILLTYPE_UNKNOWN` whereby the Courseplay script cant/wont fill from a trigger.

**Comment by sootysax** [comment]
yes - 

https://dl.dropboxusercontent.com/u/36294746/FS15%20Placeable%20Soil%20Mod%20Tanks.zip

**Comment by DeckerMMIV** [comment]
After some tests and added print()'s to Courseplay's script, I think the problem is due to how Courseplay determines what a fill-trigger is.

In `triggers.lua` function `courseplay:updateAllTriggers()` there is a check for:

```
...
  -- SprayerFillTriggers
  elseif trigger.fillType and trigger.fillType == Fillable.FILLTYPE_FERTILIZER then
      trigger.isSprayerFillTrigger = true;
      courseplay:cpAddTrigger(triggerId, trigger, 'sprayer', 'nonUpdateable');
      courseplay:debug('\t\tadd SprayerFillTrigger', 1);
...
```

So Courseplay will only recognize fill-triggers that has fill-type `fertilizer` as 'sprayer-fill-triggers'. But since your placeables have other fill-types (`fertilizer2`, `fertilizer3`, etc.), Courseplay will not take them into consideration.

I modified that if-statement in Courseplay, added SoilMod's fill-types, and ran an in-game test again. - Now Courseplay recognized the placeable PK fertilizer tank (i.e. fill-type `fertilizer2`.)

So the "solution" would be to somehow make Courseplay recognize the extra/new fill-types that  'sprayer-fill-triggers' could contain. Possibly SoilMod could call a "plugin"-method in Courseplay, to make Courseplay aware of the new fill-types.

_Edit_: Or maybe change the order of tests in Courseplay's `courseplay:updateAllTriggers()`, so anything that is not a 'GasStation', 'WaterTrailerFillTrigger' or has fill-type `seeds`, then set it as a 'SprayerFillTrigger'.

**Comment by tater99** [comment]
Hey guys.  I stumbled on to this solution myself before seeing this thread.  Adding additional elseif statements for SM fillTypes in triggers.lua works very well.

I have submitted a request on the Courseplay github to add this to CP.

**Comment by sootysax** [comment]
could you post the lines of code that you changed so we can give it a shot ourselves?  or maybe modified triggers.lua file?

**Comment by tater99** [comment]
At lines 430 - 432 of triggers.lua, there is a elseif statement for sprayer fill triggers.  

I just duplicated this elseif statement ten times and changed 'fertilizer' to a new SoilMod fillType.  'fertilizer2', 'fertilizer3', 'herbicide', etc.. 

modified script link
https://www.dropbox.com/s/wjo6pse6h40qkzy/triggersLua.zip?dl=0

My scripting knowledge is limited, so there may be a more elegant method of achieving the same end result.

**Comment by sootysax** [comment]
Awesome - the modified triggers.lua also fixes the fill issue with my Placeable Soid Mod tanks!

Perhaps we can make them look the same - and release them together (placeable and GE verisions)..  I think both our tanks are remodded versions of the same placeable tanks on the Farming Simulator.com site...

https://dl.dropboxusercontent.com/u/36294746/SoilModTanks.zip

**Comment by tater99** [comment]
Yeah, pretty much.  I think we all used the Giants water tank model.

A joint release sounds like a good idea to me.  I already have you in the credits for my version anyway regarding your influence on my view of the whole project.  I never really thought much about Courseplay until you brought it up.  I agree now that using CP for fert and herbicide spreading actually gives individual tanks a real functional purpose.  For players that do all their own spreading manually, the tanks are just a nice alternative.

Decker really helped me out a lot with the 2.0.26 update.  My GE tanks no longer need a script.  A map maker just needs to stick them on a map in GE and they are good to go.  Since the need for a script is gone, I am planning on waiting until 2.0.26 or greater goes to public release status.  What are your thoughts on that?

I'll download the placeables and take a look.  Should have some time later today or tonight.  I've got some neighbors coming over shortly to throw some sausage and ribs on the grill. :)

After I get a look at them, I'll send you a PM at FS-UK so we don't totally hijack the SoilMod github.  We can plan a course of action from there.  Mine have evolved enough that a new WIP topic might be in order anyway for a combined project.
