### ISSUE TITLE
Suggestion: Spray type stacking / Moisture should be applied hourly

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#16]
I feel like you should be able to spray multiple types of liquid fertilizer in one day, and be able to stack the level of moisture that is applied.   (if you spray fertilzer, herbicide and water - you should get 3x moisture added).

If you already have a script that runs every hour when it is raining and only effects moisture levels, maybe soilmod should run every hour when it is not raining as well, and only apply moisture that has been added.    If you run 3 different sprays in three different hours, you could get the moisture of all three sprays.

**Comment by DeckerMMIV** [comment]
There is a top-maximum of only 7 levels for 'soil moisture', so wouldn't that be reached pretty quickly during a single day, if what you suggest is implemented?

What is you reason for suggesting this 'stacking of moisture levels'? - I have not yet actually "played for a long time" with SoilMod for FS15, so if you have discovered some balancing issues which shows themself only after several in-game days/weeks, then please explain what you observe.

**Comment by sootysax** [comment]
it just seems to me that my fields run pretty dry in general and i feel like i spraying alot of liquid on the fields.  i usually will always use liquid fertilizer over solid, and only use my solid spreader for lime.

i believe that even if i spray both liquid npk and herbicide in one day, only one moisture level is gained, is that correct?

is there documentation over how moisture levels effect harvest yields?  maybe im over worrying about it.

**Comment by DeckerMMIV** [comment]
Yes. Slurry, liquid fertilizer & herbicide at the same time, will only contribute with _one_ increment in the 'soil moisture' - due to the "darkened texture".

Though you could spray water, which will contribute with _one + one_ increment; the "darkened texture" plus an additional non-disclosed layer for water. Doing so will increment the 'soil moisture' by 2.

However, just as in real life, it is difficult to control the environment ;-)

The documentation I am just working on for the upcoming first public release. Here's a preview:

```
_Water, sun and rain_

The soil's moisture is affected by water and heat.

When spraying slurry, liquid fertilizer or herbicide, the ground's moisture will be increased slightly during the nightly growth-cycle. There is also possibility to actually spray water, if it is needed.

Bad weather - i.e. rain - will increase the ground's moisture too, and does this instantly every hour.
Good weather - i.e. temperature above 22 degrees - will at noon 12:00 o'clock decrease the ground's moisture.

During harvest, the soil moisture will affect yields, from the following curve:

x0 = 50%
x1 = 70%
x4 = 100%
x7 = 70%
```

**Comment by sootysax** [comment]
you should probably list the moisture content in percentage as it does in the game, instead of x0, x1, x4, x7 -  to avoid confusion. 

As far as stacking goes, can I put multiple layers of slurry, NPK, PK, N down in the same day to compound the fertlizer level in the next growth cycle?

If so, I don't think I can go around with the sprayer and lay down a double liquid NPK layer.  But what about using one liquid and one solid NPK?  is there a distinction between liquid and solid fertilizer?

What if I liquid spray NPK and then another go around with N or PK?

**Comment by sootysax** [comment]
as far as stacking goes, if I add combinations of slurry, npk, n and pk on the same day, Will it compound the fertilizer levels during the next growth
cycle?

**Comment by DeckerMMIV** [comment]
Stacking:

```
<FoliageSubLayer name="fmc_manure"     .. numDensityMapChannels="2" ..
<FoliageSubLayer name="fmc_lime"       .. numDensityMapChannels="1" ..
<FoliageSubLayer name="fmc_fertilizer" .. numDensityMapChannels="3" ..
<FoliageSubLayer name="fmc_weed"       .. numDensityMapChannels="4" ..
<FoliageSubLayer name="fmc_slurry"     .. numDensityMapChannels="2" ..
<FoliageSubLayer name="fmc_herbicide"  .. numDensityMapChannels="2" ..
<FoliageSubLayer name="fmc_water"      .. numDensityMapChannels="2" ..
```
- Manure is 'one layer'.
- Slurry is 'one layer'.
- Lime is 'one layer'.
- Fertilizer is 'one layer' (any of the NPK combinations including liquid/solid).
- Herbicide is 'one layer' (any of the A/B/C/AA/BB/CC).
- Water is 'one layer'.
- The "darkened texture" is 'one layer' (from the base game's `terrainDetail` <DetailLayer>).

So "yes"; you can get both the slurry and the fertilizer's nutrition effects within the same growth-cycle, as they are different layers.

But "no"; you can _not_ put down NPK **and** PK in the same area within the same day, because both of these belong to the same 'one layer'. So the last type you spray, will be the one that is there, when the growth-cycle commences.

Similar, you can _not_ put down multiple different herbicide types in the same area within the same day. It will always be the last type you spray that "wins". 

:exclamation: Though the SoilMod-panel may sometime show a different/wrong herbicide-type, due to the _not-possible-to-calculate-precisely_ foliage-sub-layer's channel data-values.
