### ISSUE TITLE
Dedicated Server Software shows 'issues' with too many TXT files in mod

### ISSUE THREAD

**Issue by mngrazy** [DeckerMMIV/FarmSim_Mod_SoilMod#22]
hi decker

please convert the *.txt files in the public release in *.xml files
the dedicated server says SoilManagement.zip have errors / warnings 
he dont like txt files in a mod

regards mngrazy

**Comment by DeckerMMIV** [comment]
Please show me a LOG.TXT from the server.

**Comment by mngrazy** [comment]
http://up.picr.de/21441515wl.png

http://up.picr.de/21441516qn.png

regards grazy

**Comment by DeckerMMIV** [comment]
Hmm. Interesting.

So the 'dedicated server software' (DSS) scans through ZIP mod's files, and "complains" if it finds file-extensions that is on some 'black-list of file-extensions' by GIANTS Software.

I currently do not see this as a problem, but more like an unusual rule in the DSS. _(Why max 2 TXT files? What is the limit on PDF? Or DOC/DOCX? Why is there even a limit?)_

Anyone knows if there is a special folder-name/-setting that will tell DSS to ignore the files?

**Comment by DeckerMMIV** [comment]
Suggestion from GIANTS, regarding these "warnings" - [link to topic on GDN](http://gdn.giants-software.com/thread.php?categoryId=20&threadId=2611):

> mostly the test gives warnings, but no errors ;) 
> So it is more or less just an advice what you could improve.
> Or it is an indication how well the map was done (mostly in terms of efficiency etc)
> 
> Sorry, but listing all tests which are done by the dedicated server is impossible.
> But it mostly checks file count and size.
> 
> No, "magic markers" are not possible.
> 
> An idea for your case might be to place the map and the additional information inside a .rar file, so that the user has to extract everything first before he has access to the map.zip
> Surely this is not the most convenient way, but it would solve the problem.
> 
> Cheers,
> Emil

So I will attempt "solve" this with the work-around, by making a .ZIP file within the mod-zip itself.

**Comment by DeckerMMIV** [comment]
Since version 2.0.25 attempting to use file-extension `.RTF` for some text-files, and converted the two `.PNG` files to `.GRLE`.
I hope this causes the DedicatedServerSoftware (DSS) to _not_ complain anymore. - I would appreciate to hear from anyone using the latest development version of SoilMod on a DSS, if this is true.

**Comment by mngrazy** [comment]
hi decker

i testet it ,,,, 8 Issues   

2 pics for you

http://up.picr.de/21744357vw.png

http://up.picr.de/21744358hx.png

regards grazy

**Comment by DeckerMMIV** [comment]
Thank you mngrazy...

And... "Argh!" >:-( .. That DedicatedServerSoftware is annoying me, with its file-extension checks.
Back to the drawing board...

**Comment by DeckerMMIV** [comment]
I'm giving up on trying get the Dedicated Server Software to not complain about the too many .TXT files and the two "unknown" .GRLE files (_why? perhaps only map-mods may contain .grle files?_)

Even .ZIP and .RAR file-extensions it will complain about, so that work-around can not be used either.

So the compromise for now is to have it reduced to these 'issues':

```
Issues (3)
Unknown file type 'Requirements_for_your_MapI3D/fmcSoilManagement/fmcSoilMod_LayerA_density.grle' 
Unknown file type 'Requirements_for_your_MapI3D/fmcSoilManagement/fmcSoilMod_LayerB_density.grle' 
Text file count too high. 7 found (max. 2) 
```

**Comment by Satissis** [comment]
We just remove the grle files on the OEB dedi server and take out the text files as well.
What it means with text files, is that you have 7 text files in the zip file, but giants only allows 2 when it scans it. These is only warnings thou and it will work fine with those warnings.

Another thing Giants dedi server don't like is too many grle files in the map zip file as well, like there might be 15 grle files for the map, but a warning is shown when there is more than 8 grle files in an map but again, these are only warnings and the map still works fine.

To fix your problem, you would have to make 2 mods.
1. One with the soilmod it self, no extra files for map makers and max 2 text files.
2. One without soilmod, but with all the tools for map makers and text files needed.

**Comment by DeckerMMIV** [comment]
@Satissis - I really do not want to make two "mods", which is why I've labeled this issue with "wontfix". I do not want map-makers/-modifiers to go hunt for the instructions-"mod", or even confuse players with 'same mod yet different' using the same version-number (_there's enough of that from private edits of mods I guess._)

As I do not run/use a dedicated server myself, I have no experience of how many 'issues' other mods may have, that the DSS complains about (i.e. 'warnings').

**Comment by Satissis** [comment]
Yep I know, that's also why I said, that they are only warnings and the game works fine with it as it is. ;)
