### ISSUE TITLE
Odd herbicide readings in soil condition hud

### ISSUE THREAD

**Issue by tater99** [DeckerMMIV/FarmSim_Mod_SoilMod#31]
Hello Decker

I noticed something odd today when spraying herbicide C.  After spraying, I drove back over the area while looking at the soil condition info hud.

The info hud shows herb A at the point where the sprayer was turned on.  A meter or so further on, the info hud shows herb B.  After a couple more meters the info hud shows herb C.

This pattern repeats when the sprayer is turned off.  The info hud cycles from C to B then A as you approach the point where the sprayer was turned off.

I wasn't sure if I could explain it properly, so I took some screenshots.  Zip file uploaded.
https://www.dropbox.com/s/tgk5rq3k4te3666/herbicideTest.zip?dl=0

The same thing happens with herbicide B.

I verified my grle sizes and tested this again with a clean mods folder and got the same results.  The tests were done with SM versions 2.0.22 and 2.0.27.  Log files are in the zip with the screenshots.

I have no idea if this is just an anomaly on the info hud, or if the spray type actually cycles when the sprayer is turned on and turned off.  Just thought I would let you know about it.

EDIT:

Update to above.  I planted all crops that dislike A and B herbicide.  Used Herbicide C between each growth stage.

The soil condition hud showed the A-B-C banding at each end of the field as before.  There was no adverse effects to the crops in the areas that showed A or B herbicide on the soil condition hud.  It seems a safe assumtion that the A-B-C banding is just an anomaly.  And all sprayed areas were actually covered with herbicide C.

**Comment by Dzi4d3k** [comment]
After reading this, I realized that we have seen similar things, but I didn't pay as much attention to this.
However I could add also that if we spray double effect herbicides (AA, BB, CC), then germination protection is also displayed wrong. It displays +1 after couple minutes (playing x1), then +2, and after next day (after midnight) it display correct +3 days.
I would also say (need to double check this) that correct herbicides is displayed after midnight (soilmod calculations).

**Comment by DeckerMMIV** [comment]
The area you sprayed is containing the correct herbicide-type. It is the info-panel that has a "problem" when getting to the edge of a sprayed area.

This "info problem" is due to how the foliage-layers and the `getDensity...()` functions work.

The 'fmc_herbicide' layer uses two bits (channels) for the herbicide-types A, B & C, so one 'pixel' can represent the values; 0, 1 (A), 2 (B) & 3 (C). - The `getGensity...()` functions works on an 'area of pixels', and will return two values; the number of 'pixels' in the area (`numPixels`), and the 'combined sum of the pixels values' in the area (`sumPixels`).

This 'combined sum of the pixels values' is the "problem", when the info-panel attempts to display what type of herbicide that is in the area. It takes the `sumPixels` divides with `numPixels`, rounds it down to a whole number, and from that value determines if it is type 0, 1 (A), 2 (B) or 3 (C).

**Example / Illustration**
- Try to imagine two checkerboards (8x8 pixel-bits), and placed on top of each other (two layers).
- You can not see which squares (pixels) are occupied by pieces on the two boards.
- What you can do is ask someone else (`getDensity...()`), by giving an area of interest to them to examine - like the 4x4 corner from A1 to D4.
- The other person (who can see the boards), will now look at the instructed area, and first count the number of pieces on the lower board (1st layer). Lets say there are 4 pieces on A1 to B2, so the lower board has a total of 4 (first half of `sumPixels`).
- Then the person looks at the upper board, and sees there are also only 4 pieces on C3 to D4. Now since this is the upper board (2nd layer) a rule instructs that that value must be multiplied by 2 (_or powers of two_), so the upper board's value is 4 \* 2 = 8 (second half of `sumPixels`).
- The total sum of both the lower and upper board then becomes 12 (due to 4 + 8).
- Lastly the other person now counts the number of squares of the area we asked for, but only does so for one layer. So the checkerboard area from A1 to D4 consist of 4x4 = 16 squares (`numPixels`).
- So these two values are now returned to us; 12 and 16.

The problem:
- Can you from these two values; 12 (`sumPixels`) and 16 (`numPixels`), figure out which squares on each individual checkerboard that is occupied by a piece?

If you can, then please let me know how.
