### ISSUE TITLE
New layers arrangment issue

### ISSUE THREAD

**Issue by Dzi4d3k** [DeckerMMIV/FarmSim_Mod_SoilMod#45]
Hi,

On map prepared with new layers arrangement instruction, there is issue with default values for NPK and PK, which are respectively 4x and 2x instead of correct 5x and 4x values. Is seems that there is issue with Layer B density file, which was not changed after update in instruction.

Regards.

**Comment by DeckerMMIV** [comment]
Please verify that you have used/copied the updated `fmcSoilMod_Layer*_density.grle` files (from v2.0.36), when using the updated `Map_Instructions.txt`, since version 2.0.36.

Both the .GRLE files were changed in the commit https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod/commit/5c03adbd87a74819344bb95cfe9c5fd423491627 (v2.0.36)

It could also be, that if your savegame folder contains the previous/old `fmcSoilMod_Layer*_density.grle` files, then when **creating a new career** the game may probably not "refresh" them from the map-mod itself. So delete the contents of your savegame folder first.

Please note:
You should NOT modify the foliage-layers in an existing already prepared map WHEN you also have an existing savegame that you want to continue on. - This is explained in https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod/issues/39#issuecomment-104366990

**Comment by Dzi4d3k** [comment]
Further explanations:
- I used new savegame
- used files from 2.0.36 release
- however I've converted GRLE files to PNG, cause I wanted to change resolution to 8192x8192 (not done yet)

Edit:
After using unchanged GRLE files - situation is the same:
pH: 6.8
moisture: 57%
NPK: 4x
PK: 2x

Edit2:
LayerB PNG files looks the same before and after 2.0.36 release. Did they should look the same?

**Comment by DeckerMMIV** [comment]
Hmm. There shouldn't be that much difference in the nutrition N & PK levels, when using the 2.0.36 .GRLE files.

Anyway... There is a work-around you can use, to change the entire map's SoilMod layer's values (_which is not recommended when playing a proper savegame - unless you really want to cheat_):
- Enable the FS15 developer controls, and start a new career on the map.
- Go into the console and use the following console command;
  `modSoilMod`, to "paint" specific SoilMod layers with new values.
- Save the game, and quit FS15.
- Copy the .GRLE files from the savegame, back to where you edit your map, thereby overwriting the map's existing .GRLE files.

This way you can design your new map, with whatever custom SoilMod layer values you want, instead of "just" using the _reference .GRLE files_.

The syntax for `modSoilMod` console-command can be seen in the last part of https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod/issues/34#issuecomment-97912568 

Examples; 

```
modSoilMod FertN 5 world         // Sets 'nutrient N' to x5 for the entire map
modSoilMod FertPK 6 world        // Sets 'nutrient PK' to x6 for the entire map
modSoilMod Soil_pH 7 world       // Sets 'soil pH' to 'normal' for the entire map
```

For soil pH values, see https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod/issues/34#issuecomment-97165349 for the internal values to use.

**Comment by Dzi4d3k** [comment]
Well, that have done the job, and as I thought provided GRLE files have wrong bits set, because correct one when converted to PNG are little more red than these in 2.0.36 release.

I suggest to update Layer B GRLE file, cause it seems that I'm the first one who tested new maps preparation instruction.

Thanks for help.

Regards.

**Comment by DeckerMMIV** [comment]
I have now tested the old .PNG files from [v2.0.22](https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod/releases/tag/v2.0.22) with the old v2.0.22 map-instructions, and found that I did set the starting values to 'N x4' and 'PK x2'.

So there is no change in these _reference files_' starting values. - The only thing I can apologise for, is not remembering this earlier. :pensive:

If I recall correctly (_which may be problematic, as illustrated above_), I think I back then did not want to have a new map start out with a 'perfect SoilMod harvest' (x2.5 yield), but only somewhat to a 'normal fertilized harvest' (x2.0 yield). So that is why the 'N x4' and 'PK x2' are as they are for starting values.

**Comment by Dzi4d3k** [comment]
Well,
That explain almost everything. It was my fault as I thought that N x5 and PK x4 are default values, cause first map which I played with SoilMod had these values set like that by author.
Your idea is very good, cause if I'm not wrong, standard fertilizer can give x2 yield, and SoildMod is first mod that gives x2.5 yield with optimal conditions.

Nevertheless I'm considering this issue as solved :smiley:
