### ISSUE TITLE
Error with AAA_64erFix.zip

### ISSUE THREAD

**Issue by Vanquish081** [DeckerMMIV/FarmSim_Mod_SoilMod#48]
What change in 2.0.44?¿

SoilMod: ERROR: Something is changing Fillable.sendNumBits!

In 2.0.36 work fine.

The error is for AAA_64erFix.zip, but with 2.0.36 no show this error.
http://marhu.net/phpBB3/viewtopic.php?f=141&t=2666

**Comment by DeckerMMIV** [comment]
When I discovered that RC-Devil made that 64erFix "mod", I had to ensure that SoilMod verified itself against wrong fill-types numbers being sent in multiplayer.

So it is a 'self-guard' in SoilMod, as the 64erFix "mod" apparently changes the `Fillable.sendNumBits` _after_ SoilManagement.ZIP have been loaded. - And since RC-Devil have not made his source-code visible (_/me wonders why_), I had to ensure that SoilMod would work correctly in multiplayer, as SoilMod (with the current code) expects the `Fillable.sendNumBits` value to NOT change after SoilManagement.ZIP have been loaded.

I could probably attempt to make some changes in SoilMod, so such "late change of sendNumBits" won't affect SoilMod.

**Comment by DeckerMMIV** [comment]
Try the v2.0.45 and tell me when in multiplayer as a client, how you experience using sprayer with spray-/fill-types that have numbers above 63, with the AAA_64erFix "mod" active too.

**Comment by Vanquish081** [comment]
What process really want to try? A field with next values:
Soil pH: 6.8
Moisture: 71%
Nutrient N: x5
Nutrient PK: x4

After spread Plant Killer and a growth-cycle (sunny day):
Soil pH: 6.4
Moisture: 86%
Nutrient N: x5
Nutrient PK: x4

The same day, after other growth-cycle, before spread with plant killer (sunny day):
Soil pH: 6.0
Moisture: 100%
Nutrient N: x5
Nutrient PK: x4

In MP.

**Comment by DeckerMMIV** [comment]
Marking it as 'solved', though without knowing if any fruit-/spray-/fill-types that has a number above 63 will work correctly in multiplayer.
