### ISSUE TITLE
hide/show panel suggestion...

### ISSUE THREAD

**Issue by Vanquish081** [DeckerMMIV/FarmSim_Mod_SoilMod#53]
Hi, may you include the option to show or hide the information panel of Soil mod in next version?

**Comment by DeckerMMIV** [comment]
It is already in. Press _and hold_ the key(s) you have assigned to the 'SoilMod:Toggle grid overlay' action. - After 1 second the info-panel will be hidden (or shown).

**Comment by Vanquish081** [comment]
Not shown in "InputBindings" I asked why, but with the key "S" I move to back, nothing else happens. 

Note: Update translation this line in moddesc_es:
text name="GerminationRemain"      text="Prevención M.Hier.:"

**Comment by DeckerMMIV** [comment]
Hmm, I guess the languages causes trouble here.
When I wrote the word "_key(s)_" I meant either "_the key_" or "_the keys_". 

The _default_ key/keys that SoilMod comes with for the action 'SoilMod:Toggle grid overlay' are;
<kbd>LEFT ALT</kbd> + <kbd>I</kbd>, 
as visible in the ModDesc.XML file:
`<input name="SOILMOD_GRIDOVERLAY" ... key1="KEY_lalt KEY_i" ... />`

But you, as the player, could have customized your own key/keys for that particular action, which is why I did not write exactly what key/keys you have to press-and-hold to hide/show the info-panel.

Again, the instruction here is to **press-and-hold-down** the keys for 1 second or more.

So if you have not changed any of the default key/keys for the SoilMod actions, then you just press-**and-hold-down** the <kbd>LEFT ALT</kbd> + <kbd>I</kbd> until the info-panel changes - which should happen after 1 second.

I have updated the modDesc_l10n_es.XML with your text.

**Comment by Vanquish081** [comment]
ahh!! ok ok!! Now I understand :+1: 

solved!
