### ISSUE TITLE
modSoilModPaint command not working

### ISSUE THREAD

**Issue by Dzi4d3k** [DeckerMMIV/FarmSim_Mod_SoilMod#55]
Hello,

I've try to use commmand modSoilModPaint with no luck. Then I've found line 216 in fmcSoilMod.lua:
`foliageName = "fmcFoliage"..foliageName`

What is the purpose of adding `fmcFoliage` to each foliage layer name? `fmcFoilage` prefix is not used in names of SoilMod layers, there is `fmc_` instead. But form my opinion it would be great not to restrict command only to SoilMod layers.

Regards.

**Comment by DeckerMMIV** [comment]
Please see [this old post](https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod/issues/34#issuecomment-97912568) (_if you haven't already_) for the possible arguments that `modSoilModPaint` takes. - Note that this console-command was previously named `modSoilMod`.

The `modSoilModPaint` console-command only works with the SoilMod foliage-layers. - Those that are 'fetched' by the script-code in [setupFoliageLayers()](https://github.com/DeckerMMIV/FarmSim_Mod_SoilMod/blob/master/SoilManagement/soilMod/fmcSoilModPlugins.lua#L69)

So that is also why the `"fmcFoliage"` is prefixed, to get the LUA variable-name using `g_currentMission[foliageName]` which contains the node-id that is to be used for the add/setDensity...() methods.

---

What would you suggest that the `modSoilModPaint` console-command must take of arguments, if it should not be restricted? - Please put some thought into it, as it may not be as easy as it sounds to make such a unrestricted 'paint' console-command.

What generic/general foliage-layer values are you thinking about, you want to 'paint' in-game?

**Comment by Dzi4d3k** [comment]
Well, I saw this past but forgot where I saw it - thanks for remanding me.
Then I wrongly read source code and question arise..
Basically idea came form situation, when I was going to test sugar beet harvesting machine mod, but haven't any prepared savegame with fully grown sugar beet fields. I know that there are lot of other methods. but this was supposed to be the fastest one.

Now sorry for my sclerosis and misunderstood, and of course thank you for, as always,  comprehensive explanation.
