### ISSUE TITLE
Map authors making maps for both GMK and Soil Mod

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#65]
I'm noticing an awful lot of maps being released with both GMK and SoilMod written into the map..   The authors saying that you should only use either GMK or Soilmod.

Unfortunately, having GMK code in the map causes Soil Mod to work incorrectly.   Specifically having Lime registered as a Fruittype will cause spreaders to be required to be filled 5 times to cover an average field.

So many maps being released this way unfortunately.. maybe an update to the instructions is needed.

**Comment by DeckerMMIV** [comment]
You should probably direct that issue to the GülleMist(Kalk)Mod authors, to tell their "users" (i.e. map-authors) to not load any GMK specific scripts in their map, if the player chooses to use SoilMod instead.

This problem will unfortunately remain for a loooong time, as map-authors isn't always quite aware of how to modify LUA-scripts.

_Maybe I should ask Marhu and team, if they could see an idea of cooperating on a future combined mod - "SoilGülleMod"? - in case there happens to be a Farming Simulator 2017 game from GIANTS._

**Comment by Stowed4Sea** [comment]
I'm loving the Two Rivers Map, which has both of those in there.  Can you tell me what to delete so I don't have that stupid GMK problem?

**Comment by Stowed4Sea** [comment]
I found a "GMM_Reg.lua" file in the script folder.  Do I just delete that to take care of the conflict with your soilmod or is there something in the main .xml or .lua file that I need to remove.

**Comment by sootysax** [comment]
deleting that should be enough...  the only major conflict i had with the GMK is that you would need to fill your lime spreader 7-10 times to cover a field... when you delete the gmmreg.lua, it fixes that and you get correct coverage for lime/kalk.

**Comment by Stowed4Sea** [comment]
awesome.  Thanks for the help even though it wasn't soil mod problem.  You guys are top notch and I couldn't play FS 15 without the soil mod.

**Comment by ExocetC3i** [comment]
I encountered a similar issue with Holzhausen 2.0. The mod zip file includes i3d maps for both the GMK version and SM version. However, the SM-prepared i3d file still has some remnants of code for GMK filltypes (kalk, manureSolid, manureLiquid) which must be removed. Additionally, there are scripts in the map zip file containing a number of GMK-related lua files. This will not only affect soilmod fertilizers (which GMK includes as fruittypes instead of filltypes) but correctly allow for chopped straw to dissipate over time (otherwise it will stay down forever).

If you find a map that has both GMK and SM prepared maps in one zip file, I would recommend deleting any and all files that are not specific to the soilmod version of the map and review the code in the i3d files, and look for any stray GMK filltypes. Every map will likely be different based on how the modder incorporated and/or cleaned GMK integration into the map structure. Unfortunately, this solution is more one for power users until the mod authors split their maps into GMK and SM specific distributions.

After cleaning out the GMK files and references everything works just fine. Like sootysax, the lime/kalk application rates were the tipoff for me as they would deplete unreasonably quickly. However, I still encounter an issue where lime/kalk is a viable filltype for sprayers, but that can be dealt with in gameplay.
