### ISSUE TITLE
Inclusion of WheelLanes, Clover and Alfalfa as a part of SoilMod Installation

### ISSUE THREAD

**Issue by sootysax** [DeckerMMIV/FarmSim_Mod_SoilMod#66]
I very much enjoy the added strategy that Wheel Lanes introduces into Soil Mod.   You need to plan your actions in the days before the crops grow, so the nutrition and moisture of the soil is sufficient so you do not have to drive a tractor through the crops after growing day 2.  Otherwise you are punished by some crop destruction if you need to spray or spread after crops are mature.

In as much as 'crop destruction' is now built into the Drive Control mod (which needs to be disabled when playing with WheelLanes), I think your WheelLanes mod should be incorporated into Soil Mod, perhaps with the ability to turn it off easily for people who dont want it.

In my experience playing with SoilMod and your WheelLanes mod, I find that having cover crops like clover and alfalfa are a requirement for successful farming.   Since you cannot drive over growth stage 3 crops with WheelLanes without losing most of it before your plow reaches it.   Having cover crops that can be plowed on day 3 without wheel destruction is needed.

Maybe updating the installation instructions to cover how to add clover and alfalfa with some supporting code and files would be a benefit in any future updates to SoilMod

**Comment by DeckerMMIV** [comment]
So basically this boils down to, that WheelLanes "conflict" with SoilMod's plow effect on crops.

Maybe I could make some _individualizing_ per crop-type, of what growth-state range it should be within, to get the plow effect.
This would need to be implemented in `fmcSoilModPlugins.fmcUpdateFmcFoliage()` somehow.

_... I think I have an idea how to do it._

**Comment by sootysax** [comment]
something to note: depending on the map maker, I've seen alfalfa registered as "luzerne", "lucerne" or "luzern"

**Comment by DeckerMMIV** [comment]
_Argh! :rage1:_

... but thank you for the information. Guess I need to add some more string-compare expressions then.

**Comment by Stowed4Sea** [comment]
Can someone tell me if this fruit destruction was ever added to the soil mod?  I'm new to this, I see you referenced it, but it looks more like referencing cover crops, instead of fruit destruction.

I'd love to get this to work, as I use drive control, which kills all crops, even after just planting.  This really bothers me because when planting in real life, you always plant your end-rows first, then you plant your long rows while turning around on your end rows.  However, I'm unable to do this with drive control.  On the converse, the ability to drive on fully grown crops and not kill them is just depressing, so I leave fruit destruction on for now.  Thanks for explaining what's what to me.

EDIT:  Wait, where do you get this "wheel lanes" mod.  It sounds like it already has what I'm looking for.    The only one I found says it is not available in MP?  Is that correct (modhoster).

**Comment by sootysax** [comment]
https://github.com/DeckerMMIV/FarmSim_Mod_WheelLanes

You have to disable crop destruction in your Drive Control preferences

**Comment by Stowed4Sea** [comment]
You have no idea how happy you have made me!

**Comment by Stowed4Sea** [comment]
So, looking at this again, how does cover crops effect the N/PK levels when growing?  For example, if you leave them in the field for too long, are they still using up N/PK every growth cycle.  I know that in real life, you get more out of soil than what it takes out, but does anyone know the specifics of how it works in game?  Are they like grass where they will keep growing indefinitely, never withering?

Do these cover crops choke out the weeds and prevent them from growing like in real life?

**Comment by sootysax** [comment]
Alfalfa and Clover consume the same amount of N/PK as any other crop.  Growing nights 1 and 2 consume 2N, 1PK, -0.2 ph, and 28% moisture.  Dont know if they wither or grow forever like grass.  

Clover and Alfalfa are excluded from wheel lane destruction on day 3.  I tweaked my wheel lanes to reduce cover crops and grass down to day 3 when driven over instead of day 2, since I would have to drive over the crop before my plow would get to it.  Unless farmers IRL plow their fields going backwards as to not drive over it, is that a thing?

when plowed adds; +5 N, +1 PK
when cultivated adds; +2 N

so there really is no gain from cultivating, you break even on N and will lose 1PK
plowing them will gain you 3N

**Comment by Stowed4Sea** [comment]
Thanks for the info.  We do not use cover crops on our farm, but some of our neighbors do.  The goal is to plant it right after harvest, and till in spring right before planting but before cover crops starts growing.  This way, it minimizes soil erosion, while preventing weed growth and still adds Nitrogen to the soil, but since it barely grew due to being frozen most of the time, it doesn't take hardly anything from the soil.

I could see how this is really hard to mimic in the game, but plowing for a net gain of 3 N seems reasonable.  Thanks for the info!

**Comment by sootysax** [comment]
see this discussion:
https://github.com/DeckerMMIV/FarmSim_Mod_WheelLanes/issues/5
